name: Ubuntu

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: install updates
        run: sudo apt-get update
      - name: install build system
        run: sudo apt-get install -y autoconf autoconf-archive automake pkg-config libtool libtool-bin libltdl-dev doxygen gcc yasm
      - name: install dependencies
        run: sudo apt-get install -y libasound2-dev libaudio-dev libjack-jackd2-dev libopenal-dev libpulse-dev libsdl1.2-dev libsdl2-dev libsndio-dev portaudio19-dev
      - name: setup parallel make
        run: echo "MAKEFLAGS=-j$(nproc)" >> $GITHUB_ENV
      - name: autoreconf -iv
        run: autoreconf -iv
      - name: ./configure
        run: ./configure
      - name: make distcheck
        run: make distcheck
